site_name: Beyond Linux From Scratch
site_description: "LFS/BLFS Builder – Custom Linux Distribution Builder"
repo_url: https://github.com/landrevillejf/beyond-linux-from-scratch

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs

nav:
  - Overview: content.md
  - LPM Package Manager: lpm.md
  - Troubleshooting: troubleshoot.md
  - Docker How-To: docker-howto.md
  - Release How-To: make-release-how-to.md
  - Testing How-To: testing-howto.md
  - Wallpaper Generator: wallpaper-generator-howto.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
