#!/bin/sh
########################################################################
# Begin kea-dhcpd
#
# Description : ISC Kea DHCP Server Boot Script.
#
# Author      :
#
# Version     : BLFS 7.0
#
########################################################################

### BEGIN INIT INFO
# Provides:            kea-dhcpd
# Required-Start:      $network
# Should-Start:        networkmanager wicd
# Required-Stop:       $network
# Should-Stop:         networkmanager wicd
# Default-Start:       2 3 4 5
# Default-Stop:        0 1 6
# Short-Description:   Starts the ISC Kea DHCP Server
# Description:         Starts the ISC Kea DHCP Server
# X-LFS-Provided-By:   BLFS
### END INIT INFO

. /lib/lsb/init-functions

case "$1" in
   start)
      log_info_msg "Starting ISC Kea DHCP Server"
      mkdir -p /run/kea
      /usr/sbin/keactrl start
      evaluate_retval
      ;;

   stop)
      log_info_msg "Stopping ISC Kea DHCP Server"
      /usr/sbin/keactrl stop
      evaluate_retval
      ;;

   reload)
      log_info_msg "Reloading ISC Kea DHCP Server"
      /usr/sbin/keactrl reload
      evaluate_retval
      ;;

   restart)
      $0 stop
      sleep 1
      $0 start
      ;;

   status)
      /usr/sbin/keactrl status
      ;;

   *)
      echo "Usage: $0 {start|stop|reload|restart|status}"
      exit 1
      ;;
esac

# End /etc/init.d/kea-dhcpd
