# _config.yml
title: Way Beyond Linux From Scratch
description: Automated LFS/BLFS distribution builder
baseurl: "/beyond-linux-from-scratch"   # if your repo is a project site
url: "https://landrevillejf.github.io"

# Theme
theme: jekyll-theme-minimal

# Plugins
plugins:
  - jekyll-relative-links
  - jekyll-seo-tag

# Markdown settings
markdown: kramdown
highlighter: rouge

# Navigation (optional)
nav:
  - Home: index.md
  - Documentation: docs/
  - Releases: https://github.com/landrevillejf/beyond-linux-from-scratch/releases

# Exclude unnecessary files
exclude:
  - builder.py
  - host/
  - lfs/
  - blfs/
  - final/
  - packages/
  - tests/